
export const LIMIT = 5

//注册
export const USER_UNLOAD = "USER_UNLOAD"
export const USER_REGIST_UNLOAD = "USER_REGIST_UNLOAD"
export const USER_REGIST_FIELD = "USER_REGIST_FIELD"
export const USER_REGIST_RESULT = "USER_REGIST_RESULT"


//登录
export const USER_LOGIN_RESULT = "USER_LOGIN_RESULT"
export const USER_LOGIN_UNLOAD = "USER_LOGIN_UNLOAD"
export const USER_LOGIN_FIELD = "USER_LOGIN_FIELD"


//设置
export const USER_SETTING_RESULT = "USER_SETTING_RESULT"
export const USER_SETTING_UNLOAD = "USER_SETTING_UNLOAD"
export const USER_SETTING_FIELD = "USER_SETTING_FIELD"
export const USER_SETTING_LOGOUT = "USER_SETTING_LOGOUT"


//用户中心
export const PROFILE_GET_RESULT = "PROFILE_GET_RESULT"
export const PROFILE_FOLLOW_RESULT = "PROFILE_FOLLOW_RESULT"

//文章
export const ARTICLES_AUTHOR_RESULT = "ARTICLES_AUTHOR_RESULT"

//单个文章
export const ARTICLE_CREATE_FIELD = "ARTICLE_CREATE_FIELD"
export const ARTICLE_ADD_TAG = "ARTICLE_ADD_TAG"
export const ARTICLE_REMOVE_TAG = "ARTICLE_REMOVE_TAG"
export const ARTICLE_CREATE_RESULT = "ARTICLE_CREATE_RESULT"
export const ARTICLE_CREATE_UNLOAD = "ARTICLE_CREATE_UNLOAD"
export const ARTICLE_GET_RESULT = "ARTICLE_GET_RESULT"
export const ARTICLE_UPDATE_RESULT = 'ARTICLE_UPDATE_RESULT'

export const ARTICLE_FAVORITE_RESULT = 'ARTICLE_FAVORITE_RESULT'
export const ARTICLE_DELETE_RESULT = 'ARTICLE_DELETE_RESULT'
//评论
export const COMMENTS_GET_RESULT = "COMMENTS_GET_RESULT"
export const COMMENT_CREATE_FIELD = 'COMMENT_CREATE_FIELD'
export const COMMENT_CREATE_RESULT = 'COMMENT_CREATE_RESULT'
export const COMMENT_DELETE_RESULT = 'COMMENT_DELETE_RESULT'
//首页
export const TAGS_GET_RESULT = 'TAGS_GET_RESULT'
export const HOME_TAG_SYNC = 'HOME_TAG_SYNC'
export const HOME_TAB_SYNC = 'HOME_TAB_SYNC'
export const HOME_PAGE_SYNC = 'HOME_PAGE_SYNC'
export const HOME_ARTICLE_RESLUT = 'HOME_ARTICLE_RESLUT'